### ISSUE TITLE
Add more clarity to submissions section of API documentation

### ISSUE THREAD

**Issue by sickmind33** [Weasyl/weasyl-apidocs#3]
The documentation on submissions feels incomplete. Information is not concise enough for me to develop with.

**Comment by charmander** [comment]
What information do you need?

**Comment by sickmind33** [comment]
The Request URL for uploading submissions. URL parameters as well. Currently trying to write a ShareX script as well as a python script for quicker uploading of files.

**Comment by charmander** [comment]
There’s currently no API endpoint to create submissions.

**Comment by sickmind33** [comment]
:(

**Comment by sickmind33** [comment]
:(
